---
- name: per user
  block:
    - set_fact:
        my_user: "{{ item }}"

    # Create user project and make him admin
    - name: check if workshop user's project for user "{{ my_user }}" exists
      shell: "oc get project {{ my_user }}"
      register: user_project
      ignore_errors: true
      changed_when: false

    - name: Create workshop user's project for user "{{ my_user }}"
      command: "oc adm new-project {{ my_user }}"
      when: user_project is failed

    - name: Annotate the project as requested by user for user "{{ my_user }}"
      command: "oc annotate namespace {{my_user}} openshift.io/requester={{my_user}} --overwrite"

    - name: Award admin permission for user "{{ my_user }}"
      command: "oc adm policy add-role-to-user admin {{ my_user }} -n {{ my_user }}"

  when: create_projects
